### ISSUE TITLE
Lagotto is not returning a 404 response on pages that don't exist.

### ISSUE THREAD

**Issue by lsh-0** [articlemetrics/lagotto#229]
Requesting a page that doesn't exist returns a "302 - Found" response and takes you to the homepage.

Lagotto version `3.9.6`

![screenshot](https://cloud.githubusercontent.com/assets/2142748/5679161/d29f8830-97f2-11e4-9611-6f14b70a5635.png)

**Comment by mfenner** [comment]
This is intentionally, but I agreed that it can be confusing. Will put in a fix to return a 404 response without a redirect instead. The API behaves as expected.

**Comment by mfenner** [comment]
![bildschirmfoto 2015-01-09 um 23 33 49](https://cloud.githubusercontent.com/assets/23151/5688494/3870a404-9858-11e4-961c-470737db9e9b.png)
