### ISSUE TITLE
a stable branch for lagotto

### ISSUE THREAD

**Issue by lsh-0** [articlemetrics/lagotto#237]
Rapid development and new features are exciting things, but we find we're expending a lot of time keeping our installation(s) up to date with re-configuration, bug fixing, re-reading docs and debugging the associated problems in the lagotto ecosystem (Ruby, Rails, RVM, Passenger, bundler deps, etc).

We would like to be able to trust a branch of lagotto as being more stable than others, that receives bug and security fixes, doesn't introduce new features and that I can safely keep on the latest revision.

**Comment by mfenner** [comment]
Thanks for the feedback. I try to use [semantic versioning](http://semver.org), which states:

* MAJOR version when you make incompatible API changes,
* MINOR version when you add functionality in a backwards-compatible manner, and
* PATCH version when you make backwards-compatible bug fixes.

I am not sure how you deploy new Lagotto versions: the latest code from the master branch, or using tags. The latter should give you control of whether you install only bug fixes or also new features: going from `3.13` to `3.14` for example means that you should expect new features.

We are getting close to the `4.0` release, and here you can expect breaking changes.

What I haven't done so far, but should start doing, is bugfixes (or patch releases) for older versions, so I will start doing that.

**Comment by mbjones** [comment]
@mfenner My $.02. We also use semantic versioning, and it makes the status very clear. Thanks.  That's very generous of you to support bugfixes for older versions.  In other open source projects that I contribute to, we've found that is really hard to sustain without paid support.  Instead, we generally support the two most recent minor release series (the current and one past) with security bugfixes for both, and non-security bugfixes and new features for the current release only. If someone were paying us for support (or willing to do the support work themselves), then it might be feasible to support old versions with bug fixes. I think larger open source projects that have tens or hundreds of contributors are in a different situation from smaller projects that are predominantly supported by just a few contributors.

**Comment by mfenner** [comment]
@mbjones you are right that supporting bugfixes for older versions is hard. What makes it easier is that we have a [status page](http://articlemetrics.github.io/status/) of all production installations of the software (currently 8), so I know what versions are currently in use in a production system.

**Comment by mfenner** [comment]
Closing the issue.

**Comment by IanMulvany** [comment]
If the major and minor versions are not stable, then you can have semantic versioning all you like, but the continuous upgrade cycle will not lead to an improved experience for people deploying the software. Perhaps we could lobby then for a designated "blessed" major version that has the goal of being the most stable version, with a range of updated major versions that we accept are not so locked down?

**Comment by lsh-0** [comment]
One of the reasons that forced us from the more stable 3.12.x versions were fixes to sources in 3.13 - 3.16 that had become broken. I didn't investigate this myself, but I didn't see any mention of those fixes backported to a 3.12.8 patch.

Could the sources be pared away into their own repository?

**Comment by ajrbyers** [comment]
I'm in agreement with Luke and Ian on this. Each new version presents it's own deployment issues which means an inordinate amount of time is spent upgrading Lagotto.

**Comment by mfenner** [comment]
Thanks for the feedback. Let me look into the issues you were having to better understand whether a) I need to do more testing before releases or the issues relate more to different server configurations, b) the documentation has to be better, and c) to handle patch and minor releases differently.

I can also look into putting sources into their own directory, but after the change to the Push API, because that will dramatically change how sources work.

What would be a reasonable release schedule of stable versions, every 3 months, every 6 months? Installing those versions will be more involved, but can be better documented and tested as is the case now.

**Comment by mfenner** [comment]
Please provide further feedback in the Lagotto discussion forum: http://discuss.lagotto.io/t/strategy-for-stable-releases/97

**Comment by lsh-0** [comment]
Thanks for starting that discussion Martin, I'll post my thoughts there presently.

**Comment by mfenner** [comment]
After the release of version `4.0`, which is now in the `master` branch, the `3.2.1` release is the latest stable `3.x` release. This release will only see maintenance fixes from now on, use the branch `3-22-stable` for this release.
