### ISSUE TITLE
Mendeley API Endpoint removed

### ISSUE THREAD

**Issue by BlackScorp** [articlemetrics/lagotto#239]
https://mendeleyapi.wordpress.com/2015/01/27/upcoming-oapi-retirement/

mendeley changed the endpoint to https://api.mendeley.com/catalog/  as request parameter iam sending now doi=doi&view=stats  to retrieve the same data

here is the API Documentation http://dev.mendeley.com/methods/#retrieving-catalog-documents 

furthermore as response you will get an array of objects and only the stats as object. maybe i could make a pull request but my ruby skills are very low

best regards

**Comment by mfenner** [comment]
Thanks for the heads up - I thought I had more time to upgrade the source to use the latest Mendeley API version. The source is now updated.
