### ISSUE TITLE
JSON response format change breaking applications that expects old format 

### ISSUE THREAD

**Issue by beghelli** [articlemetrics/lagotto#254]
Sometime after Lagotto 3.6, the API v3 changed the format of the JSON response, breaking applications that expect the old format (like all the OJS clients). 

The response used to come in an array with one element: 

    response[0].sources 

Now getting the sources can be done in the following way: 

    response.sources

While the change makes sense, it breaks clients that are deployed and beyond our control.

**Comment by mfenner** [comment]
@beghelli could you give me an example API call? I am not aware of such a  change in the v3 API.

**Comment by beghelli** [comment]
http://pkp-alm.lib.sfu.ca/api/v3/articles/info:doi/10.3402/fnr.v50i1.1555?api_key=theAPIKeyHere

But testing this only (with an actual api key, of course) gave me an answer like that:
[{"doi": ........ }]
So I think that's not related with any API change... it might be something that changed on our side. Thanks for your attention.

**Comment by jalperin** [comment]
we downgraded our install again. so it may still be an issue

**Comment by mfenner** [comment]
Fixed in #321.
