### ISSUE TITLE
optionally serve v3 API responses for single works as array

### ISSUE THREAD

**Issue by mfenner** [articlemetrics/lagotto#321]
For backwards compatibility with the API format until Lagotto 3.8, i.e. before switching from *rabl* to *jbuilder* for JSON rendering.

**Comment by jalperin** [comment]
Thanks.

**Comment by mfenner** [comment]
As said in the [forum post](http://discuss.lagotto.io/t/somewhere-between-3-6-and-3-21-api-v3-changed-format/127/7?u=mfenner), please put the following into your `.env` file and restart the server:
```
# return JSON for single works as array in v3 API
API=rabl
```
