### ISSUE TITLE
Fix failing rspec acceptance tests

### ISSUE THREAD

**Issue by mfenner** [articlemetrics/lagotto#380]
`bin/rspec spec/features` has failing tests:
```
Finished in 1 minute 42.9 seconds (files took 1.9 seconds to load)
79 examples, 15 failures
```
Some failures are related to the Persona single sign-on. We can use CAS or ORCID for running the tests. The future of Persona is unclear, so we shouldn't spend too much time fixing tests related to Persona.

**Comment by mfenner** [comment]
Related to this: #385 fix `_travis.yml` configuration.

**Comment by mfenner** [comment]
Screenshots of failing acceptance tests (using `capybara-screenshot` gem) are in `tmp/capybara`.

**Comment by zdennis** [comment]
One of the issues seems to be that `memcached` is starting up but is not properly running on the TravisCI box. 

Output of ps aux | grep memcache:

```
nobody    2258  0.0  0.0 333412  1492 ?        Sl   20:16   0:00 /usr/bin/memcached -v -m 48 -p 11211 -u nobody -l 0.0.0.0
travis   22467  0.0  0.0   4352   648 pts/0    S+   20:24   0:00 sh -c ps aux | grep memcache
travis   22469  0.0  0.0   9336   940 pts/0    S+   20:24   0:00 grep memcache
```    

Output of lsof -i :11211

```
```

Yep empty.

If we start memcached without using the built-in TravisCI service then it seems to work fine.

**Comment by zdennis** [comment]
#### works.tracked

@mfenner, in commit 8ac0cf907feadfe3c631f60af0f8f57fbc86b364 you changed the default value for `works.tracked` from `true` to `false`. This is causing issues in `spec/features/works_page_spec.rb` because the works created aren't tracked and aren't showing up by default. 

I'm not sure what the appropriate resolution is. Can you take a look?

**Comment by mfenner** [comment]
Thanks for catching this. The proper resolution would be a `tracked` checkbox, which exists in the `edit` page, but not the `new` page. This checkbox should then be checked in the test.

**Comment by mfenner** [comment]
I think I want to change the session_store back to `cookie_store` instead of `ActionDispatch::Session::CacheStore`. Memcached is required to properly run Lagotto, but these errors are a little obscure. A user of the lagotto application has in the past run into the same issue when memcached was not running in production and he was unable to login.

The alternative would be to show a proper error message, but I have no strong needs to use the Rails cache anyway.

**Comment by mfenner** [comment]
A properly running memcached is still required in Travis, e.g. to run the tests checking proper caching of the APO.
